### ISSUE TITLE
Project overlap, differences from zaquestion/lab

### ISSUE THREAD

**Issue by bzub** [lighttiger2505/lab#65]
Hi, thanks for working on this gitlab CLI project! I find it very useful, especially the issue editing features.

I'm curious how the design or roadmap of this project compares to [zaquestion/lab](https://github.com/zaquestion/lab)? I'd like to contribute to one of these projects but I'm not sure which one. Thanks again.

BTW, I opened a similar ticket in the other project: https://github.com/zaquestion/lab/issues/220

**Comment by lighttiger2505** [comment]
Thank you for the question. Actually, I am also worrying about that matter.

# Premise

I can not return a express answer to your question.
I can do is to describe the differences in the feature and designs of the tools I made and the tools that @zaquestion made.
And it is only to ask "Which one do you like?".

# Differences

I believe there is not much feature difference.
I have seen the code of `zaquestion/lab`. There was not much difference between my tool and what I did in internal processing.
But his code was a little cleaner than the code I wrote.

The biggest difference will serve as an alias for hub and git.
My tool does not have this function. I will not add any plans.

https://github.com/zaquestion/lab#hub----hublab

# Design

The design of the command is very different, and my tool has a subcommand hierarchy shallow and complicated option.
The reason for this is because we place importance on accessing functions faster than simplicity.
On the other hand `zaquestion/lab` have a deep hierarchical subcommand. This is simple and easy to understand, it is a modern design.

**Comment by bzub** [comment]
That does help me understand your design goals a bit, thank you very much! Personally I'm hoping to add comments to issues/MRs via CLI, so I'll look into what that takes on both projects next probably.
